version: "3"
services:
  api:
    image: demo4
    container_name: demo4_cont
    networks:
    - myTestnetwork
    ports:
    - 3000:3000
    volumes:
    - data:/opt/apt/data

networks:
  myTestnetwork:
    driver: bridge

volumes:
  data: