version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile_Description
    restart: always
    container_name: api
    volumes:
    - ./.env:/opt/app/.env
    networks:
    - myNet
    depends_on: 
    - rmq
  rmq:
    image: rabbitmq:3-management
    restart: always
    networks:
    - myNet
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
networks:
  myNet:
    driver: bridge
  