version: '3'

services:
  frontend:
    image: svmyhome/time-app-frontend
    restart: always
    ports:
      - '3000:3000'
  api:
    image: svmyhome/time-app-api:v1.1.0
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
volumes:
  mysql_data_pub: